"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { ChevronDown } from "lucide-react"

const faqs = [
  {
    question: "How does Ignition differ from standard LLM code reviewers?",
    answer: "Most tools use a single LLM prompt to review an entire PR. Ignition uses a deterministic multi-agent workflow (LangGraph) where specialized agents (Structural, Logic, Security) run in parallel, followed by a Critic agent that synthesizes findings and eliminates hallucinations."
  },
  {
    question: "Does it support my programming language?",
    answer: "Yes, Ignition is language-agnostic at the AST parsing level. It supports JavaScript/TypeScript, Python, Go, Rust, Java, and C++. The underlying LangChain extractors map language-specific constructs into a unified context object for the AI."
  },
  {
    question: "Is my code secure?",
    answer: "Absolutely. Ignition is built for enterprise environments. Code is never used to train our models. We offer self-hosted deployment options, and our SOC2 Type II compliance guarantees strict data perimeter controls."
  },
  {
    question: "How does the Auto Fix feature work?",
    answer: "When a vulnerability or anti-pattern is detected, the agent generates a verifiable patch. You can review the diff inside the Ignition dashboard and apply it directly to your GitHub PR with a single click."
  },
  {
    question: "What is the Architecture Compliance Score (ACS)?",
    answer: "ACS is a proprietary metric generated by the Structural Agent. It tracks the health of your repository over time by evaluating SOLID principles, dependency coupling, and technical debt accumulation."
  }
]

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  return (
    <section id="faq" className="py-24 relative z-10">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-4xl font-bold tracking-tight text-foreground mb-4"
          >
            Frequently Asked Questions
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-lg text-muted-foreground"
          >
            Everything you need to know about the platform.
          </motion.p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, i) => {
            const isOpen = openIndex === i
            return (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className={`border rounded-2xl transition-colors duration-300 ${isOpen ? "bg-card border-primary/50 shadow-[0_0_15px_rgba(255,69,0,0.1)]" : "bg-card/50 border-border hover:border-primary/30"}`}
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="w-full flex items-center justify-between p-6 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-primary rounded-2xl"
                >
                  <span className="text-lg font-semibold text-foreground">{faq.question}</span>
                  <ChevronDown className={`w-5 h-5 text-muted-foreground transition-transform duration-300 ${isOpen ? "rotate-180 text-primary" : ""}`} />
                </button>
                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeInOut" }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-6 text-muted-foreground leading-relaxed">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
